name: Main
on:
  push:
    branches:
      - main

jobs:
  run-action-from-other-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: studuffy-moia/actionz/.github/actions/test@main
        with:
          who-to-greet: "stu"
